---
title: "COVID-19 European Cluster Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r recentday_cluster_analysis}

set.seed(1)

#I subset the data only to the most recent recorded day of data
covid_cluster <- covid_europe %>% 
  group_by(location) %>% 
  filter(date==max(date)) %>% 
  ungroup() %>% 
  select(c("total_cases","new_cases","total_deaths","new_deaths","new_cases_smoothed","total_cases_per_million","new_cases_per_million","new_cases_smoothed_per_million","total_deaths_per_million","new_deaths_per_million","new_deaths_smoothed_per_million","stringency_index","population_density","median_age","aged_65_older","gdp_per_capita","hospital_beds_per_thousand","human_development_index")) %>% 
  na.omit()

#train k-means clustering (and display cluster sizes via graph=TRUE)
model_kmeans_2clusters<-eclust(covid_cluster, "kmeans", k = 3,nstart = 50, graph = TRUE)

#check components
summary(model_kmeans_2clusters) 

#obtain the size of the clusters
model_kmeans_2clusters$size

# add clusters info the data frame
userdata_sel_clusters<-mutate(covid_cluster, cluster = as.factor(model_kmeans_2clusters$cluster))

```

#CLUSTER CENTERS

```{r}

#new data frame with cluster centers and cluster numbers
cluster_centers<-data.frame(cluster=as.factor(c(1:3)),model_kmeans_2clusters$centers)

#transpose this data frame
cluster_centers_t<-cluster_centers %>% gather(variable,value,-cluster,factor_key = TRUE)

#plot the centers for k=2
graphkmeans_2clusters<-ggplot(cluster_centers_t, aes(x = variable, y = value))+  
  
  #using a line plot
  geom_line(aes(color =cluster,group = cluster), linetype = "dashed",size=1)+
  
  #with connected points
  geom_point(size=1,shape=4)+geom_hline(yintercept=0)+theme(text = element_text(size=10),
        axis.text.x = element_text(angle=45, hjust=1),)+
  
  #and a relevant theme
  theme_fivethirtyeight() + theme(axis.title = element_text())



graphkmeans_2clusters


```


#PCA CLUSTERS

```{r}

fviz_cluster(model_kmeans_2clusters, userdata_sel, palette = "Set2", main="K-Means Cluster Plot Across Two Principal Components",subtitle="All Variables are Log Transformed to Mitigate the Effect of Outliers", x="Dimension 1 (10.9%)", y="Dimension 2 (9.6%)", legend.title="Cluster")+theme_fivethirtyeight() + theme(axis.title = element_text())

```

